//maincetegory
export const ADD_MAINCETEGORY = "ADD_MAINCETEGORY"
export const ADD_MAINCETEGORY_RED = "ADD_MAINCETEGORY_RED"
export const GET_MAINCETEGORY = "GET_MAINCETEGORY"
export const GET_MAINCETEGORY_RED = "GET_MAINCETEGORY_RED"
export const UPDATE_MAINCETEGORY = "UPDATE_MAINCETEGORY"
export const UPDATE_MAINCETEGORY_RED = "UPDATE_MAINCETEGORY_RED"
export const DELETE_MAINCETEGORY = "DELETE_MAINCETEGORY"
export const DELETE_MAINCETEGORY_RED = "DELETE_MAINCETEGORY_RED"
